export const GET_MAPPERS = 'GET_MAPPERS';
export const GET_MAPPERS_SUCCESS = 'GET_MAPPERS_SUCCESS';

export const GET_MAPPINGS = 'GET_MAPPINGS';
export const GET_MAPPINGS_SUCCESS = 'GET_MAPPINGS_SUCCESS';

export const ADD_MAPPING = 'ADD_MAPPING';
export const REMOVE_MAPPING = 'REMOVE_MAPPING';
